### ISSUE TITLE
Add support for merging MR

### ISSUE THREAD

**Issue by Typositoire** [swisscom/gitlab-merge-request-resource#18]
It'd be nice to be able to merge the MR from this resource.

**Comment by avanier** [comment]
Yep, that'd be nice.

**Comment by mastertinner** [comment]
I guess you're talking about https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr. Do you guys have any suggestion on where to implement it? I guess it would have to be a set of parameters on the `out` script but that's not going to be very easy because currently the out script doesn't know about the merge request so it's missing the `merge_request_iid` parameter. That would need to be passed to it somehow because currently only the `check` script knows about it.

**Comment by Typositoire** [comment]
Sorry about the delay in response :p 

The way the Github version works is actually on OUT. Dunno if you could kind of mimic what's been done there. https://github.com/jtarchie/github-pullrequest-resource
